- type: execute
  id: ac1
  urn:  www.vt.com/soar-services/v1/checkIpReputation
  params:
    ipv4Addr: "@alert:srcIp"

- type: execute
  id: ac2
  urn: www.vt.com/soar-services/v1/checkIpReputation
  params:
    ipv4Addr: "@alert:dstIp"

- type: "if"
  id: if3
  condition: "@node:ac1$reputationScore == 50"
  onFoo:
    - type: "execute"
      id: "ifYesAc1"
      urn: "www.rptsec.com/sms/v1/getDomainForIp"
      params:
        ipv4Addr: "@alert:srcIp"
  onTrue:
    - type: "execute"
      id: "ifYesAc1"
      urn: "www.rptsec.com/sms/v1/getDomainForIp"
      params:
        ipv4Addr: "@alert:srcIp"

    - type: "execute"
      id: "ifYesAc2"
      urn: "www.vt.com/soar-services/v1/checkDomainReputation"
      params:
        domainName: "@node:ifYesAc1$domainName"

  onFalse:
    - type: "execute"
      id: "ifNoAc1"  
      urn: "www.vt.com/soar-services/v1/checkIpReputation"
      params:
        ipv4Addr: "192.168.0.4"

- type: "execute"
  id: "ac4"
  urn: "www.vt.com/soar-services/v1/checkIpReputation"
  params:
    ipv4Addr: "192.168.0.5"